[project]
name = "jasacode"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "torch>=2.9.1",
    "pytorch-lightning>=2.0.0",
    "transformers>=4.0.0",
    "numpy>=1.24.0",
    "pandas>=2.3.3",
]
